### ISSUE TITLE
问下当前数据传输buffer设置8192能不能拉满带宽，能否像sftp一样并发写入提升速度

### ISSUE THREAD

**Issue by zundaren** [xiwh/zmodem#1]

**Comment by xiwh** [comment]
我本地测试能轻松跑满500M带宽，golang的sftp库需要并发写入本地才能堪堪达到100M带宽速度我认为是代码实现的问题导致吞吐率不高，实际在非高延迟大部分的场景下单线程IO才是效率最高的，只有需要非常大的带宽传输或者有非常高的延迟(因为TCP拥塞控制原因导致空闲等待时间更长) 才需要考虑多线程+多连接提升速度，当然前提是协议支持随机读写，很明显zmodem这个古老的协议对这方面支持不佳，能稳定运行起来就不错了

**Comment by zundaren** [comment]
> 我本地测试能轻松跑满500M带宽，golang的sftp库需要并发写入本地才能堪堪达到100M带宽速度我认为是代码实现的问题导致吞吐率不高，实际在非高延迟大部分的场景下单线程IO才是效率最高的，只有需要非常大的带宽传输或者有非常高的延迟(因为TCP拥塞控制原因导致空闲等待时间更长) 才需要考虑多线程+多连接提升速度，当然前提是协议支持随机读写，很明显zmodem这个古老的协议对这方面支持不佳，能稳定运行起来就不错了

好滴，大佬很强
