### ISSUE TITLE
大佬，下载那里有reader可以计算进度条，上传那里能否设置writer或者提供一个回调函数知道传了多少字节

### ISSUE THREAD

**Issue by zundaren** [xiwh/zmodem#3]
OnUpload: func() *zmodem.ZModemFile {
  uploadFile, _ := zmodem.NewZModemLocalFile("/root/test/aa")
  return uploadFile
}

**Comment by xiwh** [comment]
你把NewZModemLocalFile改成NewZModemFile拿到writer自行处理文件的io拷贝，每次写入或读取前加个计数就能拿到进度

**Comment by zundaren** [comment]
> 你把NewZModemLocalFile改成NewZModemFile拿到writer自行处理文件的io拷贝，每次写入或读取前加个计数就能拿到进度

之前用NewZModemFile往里面写数据会卡住，不知道修复没，我再试下

**Comment by xiwh** [comment]
需要开一个goroutine再写入，不能卡住return
