### ISSUE TITLE
上传，下载的问题

### ISSUE THREAD

**Issue by zundaren** [xiwh/zmodem#4]
上传时服务器如果存在相同文件会卡住， 上传中断writer正常
下载时突然中断writer, 会卡住, return err 或 return nil无法正常退出

无法响应 ctrl+c中断，会生成错误文件，该文件无法正常删除 
![image](https://user-images.githubusercontent.com/44863479/230718924-a97978df-9448-4b33-89a8-de5b5161482d.png)

**Comment by xiwh** [comment]
"上传时服务器如果存在相同文件会卡住， 上传中断writer正常" 这个已修复
"下载时突然中断writer, 会卡住, return err 或 return nil无法正常退出"  这个提升了一定的稳定性，需要注意的是关闭writer后任需要等待一定的时间（zmodem协议貌似没有规定下载中途结束的指令，只能尝试发送强制结束指令，需要等待接收端处理有一定延迟,可能是几百毫秒到几秒）终端才可能正常回显
“无法响应 ctrl+c中断，会生成错误文件，该文件无法正常删除" 无法响应 ctrl+c中断和实现机制和协议限制的问题，暂时不打算实现这一块功能，你可以尝试自行监听输入^c强制close wirter（不保证可用) , 生成错误文件我本地未复现出来。

最后由于zmodem协议不是一个标准严谨的协议每个种实现都会有细微的区别，所以功能上并不保证完全百分比稳定，有时候可能还是会有问题，目前只能做到常用的大多数操作在大多数情况是正常的

**Comment by zundaren** [comment]
> "上传时服务器如果存在相同文件会卡住， 上传中断writer正常" 这个已修复 "下载时突然中断writer, 会卡住, return err 或 return nil无法正常退出" 这个提升了一定的稳定性，需要注意的是关闭writer后任需要等待一定的时间（zmodem协议貌似没有规定下载中途结束的指令，只能尝试发送强制结束指令，需要等待发送端处理有一定延迟,可能是几百毫秒到几秒）终端才可能正常回显 “无法响应 ctrl+c中断，会生成错误文件，该文件无法正常删除" 无法响应 ctrl+c中断和实现机制和协议限制的问题，暂时不打算实现这一块功能，你可以尝试自行监听输入^c强制close wirter（不保证可用) , 生成错误文件我本地未复现出来。
> 
> 最后由于zmodem协议不是一个标准严谨的协议每个种实现都会有细微的区别，所以功能上并不保证完全百分比稳定，有时候可能还是会有问题，目前只能做到常用的大多数操作在大多数情况是正常的
